### ISSUE TITLE
SmartTemplates should switch BCC on account change in composer as configured in TB

### ISSUE THREAD

**Issue by tvamana** [RealRaven2000/SmartTemplate4#37] opened 2020-01-18 09:14 UTC
Hi, I use several accounts in TB and in the settings of each accounts I have a special Bcc email preconfigured for backup purposes (standard accounts settings as they come with TB (in my localized version of TB this item is called "Copise and folders", it is the second subitem in the list under each account). Before I installed ST as well as now with ST disabled, it behaves as it should - in compose window when I change the account that I will be using for sending the message, the Bcc field updates to the correct address preconfigured for the particular account. With ST enabled it des not update anymore so after I change account the Bcc is wrong.

The same happens to my addon "Copy Sent to Current" that I use. Normally on account change the default folder for saving the message copy changes accordingly. With ST enabled it does not change as it should.

Thanks for helping

**Comment by RealRaven2000** [comment] 2020-01-18 09:36
Thanks I will look into this. Are you using any `%header.set..%` commands?

>The same happens to my addon "Copy Sent to Current" that I use. Normally on account change the default folder for saving the message copy changes accordingly. With ST enabled it does not change as it should.

I use CS2C, too. Current is normally the folder of the originating mail, what do you expect it to do?

**Comment by tvamana** [comment] 2020-01-18 09:58
I am using no commands at all. Just started using ST and only thing I am doing so far is I I have manually copied HTML source of my templates created previously for Stationery into all three fields (write, reply, forward) under the individual accounts in ST settings. So pure HTML, no commands.

(BTW I would very much prefer if I could simply point to my existing HTML file on hard disk rather than copying the HTML manually in the field...)

As for CS2C I use it to quickly choose when sending a message between two options - either 1) I want to keep the copy of the sent message in the Sent folder of tat particular account, or 2) I want the message to go to Trash of that particular account where I could still find it for a short period of time if needed but after a while it gets deleted automatically as set in TB settings. However in both cases I again need that the Sent and Trash folders offered are those that belong to the particular account that I am using to send the message from. And again without ST this updates immediately as soon as I change this account in the compose window, but with ST enabled it does not change so it would store the copy of the message in either Sent or Trash of the account that was originally selected when I opened the compose window rather than the account that I finally chose for sending the message.

**Comment by RealRaven2000** [comment] 2020-01-18 12:22
> (BTW I would very much prefer if I could simply point to my existing HTML file on hard disk rather than copying the HTML manually in the field...)

Totally, click on the %file% command, it will prompt you for your template location and then insert the necessary command to pull the template(s):

![image](https://user-images.githubusercontent.com/6314674/72663594-399ee080-39ec-11ea-8880-6e174d35b38e.png)

> As for CS2C I use it to quickly choose when sending a message between two options - either 1) I want to keep the copy of the sent message in the Sent folder of that particular account, 

Alright, I never use the Sent folder. And also trying to keep my inbox clean - everything gets threaded & archived in topical folders. But that's just personal preference from using QuickFolders for such a long time.

> or 2) I want the message to go to Trash of that particular account where I could still find it for a short period of time if needed but after a while it gets deleted automatically as set in TB settings. 

Alright. If anything goes to trash I don't read it anymore. :) YMMV

>I need that the Sent and Trash folders offered are those that belong to the particular account that I am using to send the message from. And again without ST this updates immediately as soon as I change this account in the compose window

How do you send it to trash from the compose window? You send a composed message to trash? weird ... my guess is you use the C2C dropdown:
![image](https://user-images.githubusercontent.com/6314674/72663655-fabd5a80-39ec-11ea-9beb-3d8fcce63f00.png)
...and that preselects a different account when you change identity? It's hard to imagine so I need a little more info here. I still can't imagine how (and why) you would select Trash after sending an email. I badly need a second email account in my test profile...

**Comment by RealRaven2000** [comment] 2020-01-18 13:04
I made a quick test with 2 Imap accounts with cross-linked bcc addresses:
![image](https://user-images.githubusercontent.com/6314674/72664093-c0a28780-39f1-11ea-87e6-ba71ef81bc34.png)

then changing the From address to the other one, with the "write" template enabled on ST4:
![image](https://user-images.githubusercontent.com/6314674/72664112-fa738e00-39f1-11ea-9b39-c4e618338c66.png)

Super strangely I cannot write an email from the second account (thunderbirddaily) it ALWAYS defaults to thunderbirddaily67 - even when I reply from the other account, Not quite sure what to think of this.

**Comment by RealRaven2000** [comment] 2020-01-18 13:14
I still have the same problem after restarting with ST4 disabled - maybe the mail addresses are too similar, so I need to make new test addresses first to see if this isn't a Thunderbird bug.

**Comment by tvamana** [comment] 2020-01-18 20:09
CS2C:
I have two "Send" buttons in the menu - the standard one called "Odeslat" (means "Send" in my localized CZ version of TB) saves copy of the message in the Sent folder where it stays forever until I delete it. I use this for messages where I expect I need to have a copy for the future. And there is another button next to the first one called "Send (no copy)" and if I use this one for sending the message, the copy of it goes to Trash, which because of my TB settings means that it will be automatically deleted after a week or two. I use this option for messages where I do not expect I will need to have a copy. I still can go to Trash and see it or move it somewhere else, especially if I hit this button as a mistake, but this is a rare scenario. This workflow prevents my Sent folders from growing with no end every day and saves me a lot of time that I otherwise would have to spend ever now and then on manual deleting unnecessary messages from Sent.

I am trying to insert a screenshot here of the two buttons, let us see if you can see it:
![obrazek](https://user-images.githubusercontent.com/60031095/72669771-23b60d80-3a36-11ea-9be7-a6fb31247ea2.png)

**Comment by RealRaven2000** [comment] 2020-01-18 20:25
Ok, so that second button "_Send (no copy)_" looks like it's from another Add-on:

![image](https://user-images.githubusercontent.com/6314674/72669981-fd8d6f00-3a2f-11ea-95ae-c91ed8b58e9c.png)
it's not even in Czech, so I guess the Add-on author didn't supply a Czech translation. I don't think it's overly important for the missing bcc issue, so I am going to ignore that part for now.

I am still having some trouble with the account changing in my test profile, so I will need to do a fresh round of tests, maybe on a different test profile tomorrow. Not too sure what is happening in Thunderbird for it not to add the bcc on changing the identity. Hopefully I will know more tomorrow.

**Comment by tvamana** [comment] 2020-01-28 12:54
> 
> 
> Ok, so that second button "_Send (no copy)_" looks like it's from another Add-on:
> 
> ![image](https://user-images.githubusercontent.com/6314674/72669981-fd8d6f00-3a2f-11ea-95ae-c91ed8b58e9c.png)
> it's not even in Czech, so I guess the Add-on author didn't supply a Czech translation. 

Yes, this is exactly from the add-on CS2C

 
> I am still having some trouble with the account changing in my test profile, so I will need to do a fresh round of tests, maybe on a different test profile tomorrow. Not too sure what is happening in Thunderbird for it not to add the bcc on changing the identity. Hopefully I will know more tomorrow.

Any progress so far?

**Comment by RealRaven2000** [comment] 2020-01-28 13:41
> > Ok, so that second button "_Send (no copy)_" looks like it's from another Add-on:
> > ![image](https://user-images.githubusercontent.com/6314674/72669981-fd8d6f00-3a2f-11ea-95ae-c91ed8b58e9c.png)
> > it's not even in Czech, so I guess the Add-on author didn't supply a Czech translation.
> 
> Yes, this is exactly from the add-on CS2C

Alright, I first thought I was missing something but it is actually there in the Composer window. I only looked at the main window. I am just a bit confused now, this (send without copy) has nothing to do with the original bug (bcc is destroyed when switching identities), right? If you need a specific solution for that one just open a new issue, but I think we got side tracked here... they may well be related.

The main thrust is that bcc is thrown away which shouldn't happen. On a quick test on my test profile, my bcc remains the same once set by the first template. You want it to be removed again (and replaced with a different bcc if it is the account is configured accordingly)

**Comment by tvamana** [comment] 2020-01-28 13:50
> Alright, I first thought I was missing something but it is actually there in the Composer window. I only looked at the main window. I am just a bit confused now, this (send without copy) has nothing to do with the original bug (bcc is destroyed when switching identities), right? If you need a specific solution for that one just open a new issue, but I think we got side tracked here... they may well be related.
I think both may be caused by the same bug in ST, because with ST disabled both work fine, with ST enabled both are broken the similar way - they dont react any more and stay "frozen" with their default setting based on the first selected account.

> The main thrust is that bcc is thrown away which shouldn't happen. On a quick test on my test profile, my bcc remains the same once set by the first template. You want it to be removed again (and replaced with a different bcc if it is the account is configured accordingly)
What I want is that the Bcc (just like the CS2C folder) change as soon as I change the account that I will be using for that particular composed message as its "From" account. That means if I have accounts A and B and in TB I have set that any mail going out from A should Bcc to email X while every mail from B should Bcc to email Y, then I need TB to keep switching Bcc field automatically between X and Y as soon as I switch From between A and B. Without ST this works with no problems, I have several accounts and can switch between them as often as I can, it follows.

**Comment by RealRaven2000** [comment] 2020-11-16 17:26
> 
> What I want is that the Bcc (just like the CS2C folder) change as soon as I change the account that I will be using for that particular composed message as its "From" account. That means if I have accounts A and B and in TB I have set that any mail going out from A should Bcc to email X while every mail from B should Bcc to email Y, then I need TB to keep switching Bcc field automatically between X and Y as soon as I switch From between A and B. Without ST this works with no problems, I have several accounts and can switch between them as often as I can, it follows.

I am wondering about closing or fixing this bug - now backporting to Tb68 as well - can you send a screenshot where you can configure this bcc field in Thunderbird? I can't seem to find that, only a "reply-to" setting...

**Comment by RealRaven2000** [comment] 2020-11-16 17:28
I found it in Tb78 - under COpies & folders. It works for me there:
![Uploading image.png…]()

**Comment by RealRaven2000** [comment] 2020-11-16 17:31
I just tested it with my Thunderbird 68, it appears to work there too, even if I switch accounts in composer window...
is it fixed or am I missing something?

**Comment by RealRaven2000** [comment] 2020-11-25 16:22
Marking as fixed for now until reopened in case it can be reproduced in Tb 78

**Closed by RealRaven2000** 2020-11-25 16:22 UTC
Labels: bug
