### ISSUE TITLE
Addon settings: compose tab not accessible

### ISSUE THREAD

**Issue by chrystalingus** [RealRaven2000/SmartTemplate4#86] opened 2020-09-24 08:46 UTC
I just tried to change the template to be used when composing, answering, forwarding and found that when I enter the "composing" tab it offers me the "answering" settings, in the "answering" tab it offers the "forwarding" settings and in the "forwarding" tab it offers the "forwarding" settings as well. Thus I cannot change my template for "composing". Screenshots attached.
![verfassen](https://user-images.githubusercontent.com/32355892/94122755-dacb1a00-fe4a-11ea-9e77-ecb4808771ec.jpg)
![antworten](https://user-images.githubusercontent.com/32355892/94122759-db63b080-fe4a-11ea-8206-c1ba6a4bb381.jpg)
![weiterleiten](https://user-images.githubusercontent.com/32355892/94122761-db63b080-fe4a-11ea-82ce-081805e5f9db.jpg)

I am using the alpha version for TB 78

**Comment by RealRaven2000** [comment] 2020-09-24 15:04
Weird - this works for me, maybe there are some settings in your templates that cause it to malfunction.... can you check JavaScript error console during switching? If you are on Windows, press ctrl+Shift+J to show it. Reset the contents before the test. Do _one_ action (such as clicking the tab to change from Write to Reply, then check for any error messages.

The other thing you might do is export your settings, using the save template button (to the right of the account picker)

![image](https://user-images.githubusercontent.com/6314674/94163192-770f1400-fe7f-11ea-8bb4-f2f0b6248b51.png)

if you don't want to post them here publicly, you can send them to my mail address by using the support tab:
![image](https://user-images.githubusercontent.com/6314674/94163282-8f7f2e80-fe7f-11ea-8009-bcbd8ff760d3.png)

**Comment by chrystalingus** [comment] 2020-09-25 07:43
Switching tabs did not create any error messages in console.

Using account "Allgemein" with nothing entered in "Kopfzeilen" or "Nachrichtenvorlage" textareas: Problem gone.

Problem occurs for the first time when switching account to one with Kopfzeilen etc entered.
Example with problem occurring:
{
  "newmsg.id6": "<p>%cursor%</p>\n<small>%file(C:\\Users\\xxxxx\\Desktop\\sig.txt)%</small>",
  "rspheader.id6": "<p>%cursor%</p>\n<small>%file(C:\\Users\\xxxxx\\Desktop\\sig.txt)%</small>",
  "rspmsg.id6": "",
  "fwdheader.id6": "<p>%cursor%</p>\n<small>%file(C:\\Users\\xxxxx\\Desktop\\sig.txt)%</small>",
  "fwdmsg.id6": "",
  "new.id6": true,
  "newhtml.id6": true,
  "newnbr.id6": false,
  "rsp.id6": true,
  "rsphead.id6": false,
  "rsphtml.id6": true,
  "rspnbr.id6": false,
  "fwd.id6": true,
  "fwdhead.id6": false,
  "fwdhtml.id6": true,
  "fwdnbr.id6": false
}

Nothing fancy at all.

Switching to an account (in the account list following the one mentioned above) with NOTHING entered (also not "Allgemein verwenden"): Problem persists!

**Comment by chrystalingus** [comment] 2020-09-25 07:46
HTML-tags used in my config are not displayed here. I will attach again 
[admin@fly-style.com - Aurel Engelmann.txt](https://github.com/RealRaven2000/SmartTemplate4/files/5281294/admin%40fly-style.com.-.Aurel.Engelmann.txt)

Had to be txt

**Comment by RealRaven2000** [comment] 2020-09-26 16:31
Which version of Thunderbird are you currently using?

**Comment by chrystalingus** [comment] 2020-09-27 10:37
I'm using TB 78.2.2 32Bit
There was just now an update to 78.3.1 (32Bit) but the problem persists.

**Comment by chrystalingus** [comment] 2020-09-27 10:41
BTW I just noticed in the console, when I open the Addon-Settings window there is no error but still a message about an exeption thrown. I'll attach a screenshot
![Screenshot 2020-09-27 113922](https://user-images.githubusercontent.com/32355892/94362918-4f55c100-00b6-11eb-9db8-86c7866d473b.jpg)

**Comment by RealRaven2000** [comment] 2020-09-27 11:48
> 
> 
> BTW I just noticed in the console, when I open the Addon-Settings window there is no error but still a message about an exeption thrown. I'll attach a screenshot

that's probably what makes it fail. It;s a missing setting. Can you try checking and then unchecking the top checkbox?
![image](https://user-images.githubusercontent.com/6314674/94364219-a8762280-00bf-11eb-8b5b-902e9f86ad35.png)

**Comment by chrystalingus** [comment] 2020-09-27 13:38
I noticed that BEFORE I use the tabs (opening the settings window and selecting an account) I am actually in the "verfassen/composing" tab. That way I managed to uncheck "apply the following..." in there as well.
I tried leaving them checked (what I want) and unchecked in all three tabs. But unfortunately that did not change anything.

**Comment by opto** [comment] 2020-10-10 11:27
latest version:
1) options dialog for email account: forward and answer tabs are identical. If forward text is set to fff, answer text wil be fff as well. Same for checkbox: check in one ab checks in other tab as well.
2) applying template:  compose works. Answer does compose action. Forward does what is entered in the commen tabs for answer and forward.
So this needs some bug searching. all in TB 78.3.2
no error in error console.

**Comment by RealRaven2000** [comment] 2020-10-10 12:44
>     1. options dialog for email account: forward and answer tabs are identical. If forward text is set to fff, answer text wil be fff as well. Same for checkbox: check in one ab checks in other tab as well.
> 
>     2. applying template:  compose works. Answer does compose action. Forward does what is entered in the commen tabs for answer and forward.

I think that switching over between the tabs (write / reply / forward) doesn't fully work for some users. So we need to investigate the tab select event.

**Comment by opto** [comment] 2020-10-13 13:49
this has been caused by a bug deep in TB. When adding the new tabs, TB doubled the spacers, and then lost count which content (=tabpanel) to display in which tab (because there was an extra spacer element that TB counted as extra tabpanel). So 'to' tab showed content of reply, 'reply' tab showed content of forward, and 'forward' tab showed into nothing.

This bug has taken us (me, opto) more than 10 hours to nail down to the actual code, and it is not even code that we have written - it is the TB glue code around tabs. So yes, I encourage you to support Axel by a donation or a licence.

I think Axel will test and then create another prerelease.
Klaus

**Comment by RealRaven2000** [comment] 2020-10-15 09:44
@chrystalingus it works for me now, have created a prerelease here, can you test please?

https://github.com/RealRaven2000/SmartTemplate4/releases/tag/3.0pre45

thanks in advance!

**Comment by chrystalingus** [comment] 2020-10-15 14:31
Very awesome! It works :) Thank you so much for your efforts.

**Comment by RealRaven2000** [comment] 2020-10-15 21:14
Many thanks to @opto for chasing this down. It was a tough one and honestly I had already debugged deep into the Mozilla code and thought it wasn't worth it for me. We will probably have to file a bug with Mozilla on this, too - but I wouldn't hold my breath for them fixing it - I don't think tab controls will ever be part of the HTML standard - I bet in 2 years they will use jQuery or some other monster libraries full of extra external code for this sort of stuff. I don't think any mere mortal understand how jQuery works under the hood - and I deeply dislike including 3rd party libraries like these because it kind of defeats the purpose of open source having something that's minified and highly complex (and working will all sort of browser quirks) as part of an Add-on that should be working with Thunderbird code, out of the box. Call me a dinosaur for it, I don't care.

I will close this issue as soon as the official version of SmartTemplate is released on ATN.

**Comment by RealRaven2000** [comment] 2020-11-16 16:54
Fixed in Release 3.0 which is available on atn.

**Closed by RealRaven2000** 2020-11-16 16:54 UTC
Labels: Tb 78, bug
