### ISSUE TITLE
Erratic %datetime()% results when forcing HTML with Shift ⬆ mode

### ISSUE THREAD

**Issue by macdeport** [RealRaven2000/SmartTemplate4#115] opened 2021-01-12 19:48 UTC
**Example**
Template:
`On %X:=sent%%dateformat(d/m/Y H:M:S)% %from(name,bracketMail())% wrote:`

[Forward/Reply] result:
`On 12/01/2021 17:14:06 James Xery <james_xery@gogle.com> wrote:`

Shift ⬆ + [Forward/Reply] result:
`On 12/01/2021&1JansPM;17:14:06 James Xery <james_xery@gogle.com> wrote:`

**Comment by RealRaven2000** [comment] 2021-01-12 20:21
Strange, thanks for reporting. You use Shift to force plaintext?

**Comment by macdeport** [comment] 2021-01-12 21:24
Here I used Shift ⬆ to open composition window in HTML mode...

**Comment by macdeport** [comment] 2021-01-14 19:58
More on this annoying bad decoding of template, perhaps to help to find a fix: 

"`&1JansPM;`" can be "`&1JansAM;`" depending the time stamp of the mail.
`28/11/2020 09:34:53` => `28/11/2020&11NovsAM;09:34:53`

I will try to play with setting...

**Comment by macdeport** [comment] 2021-01-14 20:37
`On %X:=sent%%d%/%m%/%Y% %H%:%M%:%S% %from(name,bracketMail())% wrote:`

in substitution of

`On %X:=sent%%dateformat(d/m/Y H:M:S)% %from(name,bracketMail())% wrote:`

seems the workaround...

**Comment by RealRaven2000** [comment] 2021-01-15 10:51
> More on this annoying bad decoding of template, perhaps to help to find a fix:
> 
> "`&1JansPM;`" can be "`&1JansAM;`" depending the time stamp of the mail.
> `28/11/2020 09:34:53` => `28/11/2020&11NovsAM;09:34:53`

So it looks like the space between the first group and second group is replaced with "`&11NovsAM;`" (depending on current day time and date)?
1 - What language is Thunderbird in?
2 - Also are you using the `%language()%` switch?
3 - If you use Shift to force HTML, is your default setting "reply with plain text"? Or does it depend on what format email you answer to?
4 - Which version of SmartTemplates are you using?

**Comment by macdeport** [comment] 2021-01-15 12:04
> 1 - What language is Thunderbird in?

![floating-screenshot-124709s](https://user-images.githubusercontent.com/26068595/104723995-5b7e9080-5730-11eb-8fd1-7d356d592b51.jpg)

US Thunderbird on a French 0SX

> 2 - Also are you using the %language()% switch?

Not yet

> 3 - If you use Shift to force HTML, is your default setting "reply with plain text"? Or does it depend on what format email you answer to?

Yes, my default  setting is "reply with plain text" and I use Shift when I have to compose HTML mail

> 4 - Which version of SmartTemplates are you using? 3.3.1

![floating-screenshot-130104s](https://user-images.githubusercontent.com/26068595/104725206-0a6f9c00-5732-11eb-821e-6bde4d095c45.jpg)

**Comment by RealRaven2000** [comment] 2021-01-15 13:08
> > 1 - What language is Thunderbird in?
> 
> en-US Thunderbird 78.6.1 on a French 0SX
> 
> > 3 - If you use Shift to force HTML, is your default setting "reply with plain text"? Or does it depend on what format email you answer to?
> 
> Yes, my default setting is "reply with plain text" and I use Shift when I have to compose HTML mail
> 
> > 4 - Which version of _SmartTemplates_ are you using? en-US 3.3.1

thanks this may be helpful. I think this should rule out translation issues, which may make it easier to reproduce.

**Comment by RealRaven2000** [comment] 2021-01-15 13:11
> **Example**
> Template:
> `On %X:=sent%%dateformat(d/m/Y H:M:S)% %from(name,bracketMail())% wrote:`

one more question - for replies / forwarding this should be in the "quote header" field (on top) - are you using it in the "template" field?

**Comment by RealRaven2000** [comment] 2021-01-15 13:20
I have created a "plaintext as default" test account, with the following settings for reply:
![image](https://user-images.githubusercontent.com/6314674/104731887-44da3880-5734-11eb-967a-39b857032aa9.png)
Couldn't as of yet reproduce the problem (en-US Thunderbird 78.6.1) replying to various (mostly html) mails.

**Comment by macdeport** [comment] 2021-01-15 15:34
> Couldn't as of yet reproduce the problem (en-US Thunderbird 78.6.1) replying to various (mostly html) mails.

This JSON template will perhaps answer to your perplexity:

`{
  "newmsg": "%cursor%\n%header.set(priority,high)%\n%sig(text)%",
  "rspheader": "%cursor%\n%header.set(priority,high)%\n%sig(text)%\n\nOn %X:=sent%%d%/%m%/%Y% %H%:%M%:%S% %from(name,bracketMail())% wrote:\n> To: %to(name)% <%to(mail)%>[[\n> Cc: %cc(name)% <%cc(mail)%>]]\n> Subject: %subject%\n> Message-ID: %Message-ID%\n[[> Reply-to: %Reply-to%\n]]>\n\n",
  "rspmsg": "",
  "fwdheader": "%cursor%\n%header.set(priority,high)%\n%sig(text)%\n\n-------- Forwarded Message --------\nOn %X:=sent%%d%/%m%/%Y% %H%:%M%:%S% %from(name,bracketMail())% wrote:\n> To: %to(name)% <%to(mail)%>[[\n> Cc: %cc(name)% <%cc(mail)%>]]\n> Subject: %subject%\n> Message-ID: %Message-ID%\n[[> Reply-to: %Reply-to%\n]]>\n\n",
  "fwdmsg": "\n",
  "new": true,
  "newhtml": true,
  "newnbr": true,
  "rsp": true,
  "rsphead": true,
  "rsphtml": false,
  "rspnbr": true,
  "fwd": true,
  "fwdhead": true,
  "fwdhtml": false,
  "fwdnbr": false
}`

Maybe I have misused "Quote Header"/"Template" fields

**Comment by RealRaven2000** [comment] 2021-01-15 16:34
OK, you almost got it right - in the reply field, move these top lines:
```
%cursor%
%header.set(priority,high)%
%sig(text)%
```
down into the "template" field. because Template represents your reply, and has nothing to do with the quote. Having said that, it should probably maybe still work if you put it into "quote header". that field is there for replacing the standard text "on xxx, yyy wrote:" and is always displayed on top of the quote. But the location of the qoute itself (as you know) is configured in Composition & Addressing:

![image](https://user-images.githubusercontent.com/6314674/104753122-790f2280-574f-11eb-9537-c66f4e5aa17c.png)

**Comment by RealRaven2000** [comment] 2021-01-15 16:39
By the way in the template you exported you are already using the workaround syntax, not `%dateformat()%`? My understanding is that the later has the problem?
`On %X:=sent%%dateformat(d/m/Y H:M:S)% %from(name,bracketMail())% wrote:`

**Comment by RealRaven2000** [comment] 2021-01-15 16:44
> By the way in the template you exported you are already using the workaround syntax, not `%dateformat()%`? My understanding is that the later has the problem?
> `On %X:=sent%%dateformat(d/m/Y H:M:S)% %from(name,bracketMail())% wrote:`

Good news - I can reproduce the problem with that setting, so shouldn't be too difficult to fix.

**Comment by RealRaven2000** [comment] 2021-01-15 16:55
Hah! I know what happened:

![image](https://user-images.githubusercontent.com/6314674/104755440-54687a00-5752-11eb-8f15-0d44c08e031e.png)

when we force the text into html mode using SHIFT the space is being converted into a nonbreaking space %nbsp; and then decoded by the formatting routine,

**Comment by RealRaven2000** [comment] 2021-01-15 17:23
try this test version - I am replacing some of the most common html entities (but not all) that are based on alphabetic sequences (`&nbsp; &tab; &copy; &lt; &gt;`)

[smartTemplate-fx-3.4pre10.zip](https://github.com/RealRaven2000/SmartTemplate4/files/5822038/smartTemplate-fx-3.4pre10.zip)

**Comment by macdeport** [comment] 2021-01-15 19:42
After restructuring "Quote Header"/"Template" fields as suggested with this template https://github.com/RealRaven2000/SmartTemplate4/issues/115#issuecomment-761049167 I experienced erratic `%datetime()%` results only in case of forwards...
Now I will try [smartTemplate-fx-3.4pre10.zip](https://github.com/RealRaven2000/SmartTemplate4/files/5822038/smartTemplate-fx-3.4pre10.zip)

**Comment by macdeport** [comment] 2021-01-15 19:56
Erratic `%datetime()%` results have disappeared...

**Comment by RealRaven2000** [comment] 2021-02-06 13:27
Fixed in:

- 3.4 Release for Thunderbird 78 - 05/Feb/2021
- 2.14 Release for Thunderbird 68 - 05/02/2021

**Closed by RealRaven2000** 2021-02-06 13:27 UTC
